// src/constants/tagKeys.js
export const TAG_KEYS = {
  AUTH: "Auth",
  USER: "User",
  PRODUCT: "Product",
  PRODUCT_VARIANT: "ProductVariant",
  PRODUCT_IMAGE: "ProductImage",
  COLOR: "Color",
  SIZE: "Size",
  ROLE: "Role",
  CATEGORIES: "Categories",
  WARD: "Ward",
  DISTRICT: "District",
  PROVINCE: "Province",
  ADDRESS: "Address",
  ORDER: "Order",
  ORDER_ITEM: "OrderItem",
  BRANCHES: "Branches",
  PROMOTION: "Promotion",
};
